-- migrate:up

-- Map local users to vas3k.club accounts via their slug (OIDC sub)
ALTER TABLE users ADD COLUMN club_user_id TEXT UNIQUE;

-- Cache of roles from vas3k.club (moderator, god, curator, bank)
ALTER TABLE users ADD COLUMN club_roles TEXT[] NOT NULL DEFAULT '{}';

-- Track when the user last received their daily 100-token bonus
ALTER TABLE users ADD COLUMN last_daily_bonus_at TIMESTAMPTZ;

-- Local market_admin role grant (separate from club roles)
CREATE TABLE market_admins
  ( id         BIGINT      NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
  , user_id    BIGINT      NOT NULL REFERENCES users (id)
  , granted_by BIGINT      NOT NULL REFERENCES users (id)
  , created_at TIMESTAMPTZ NOT NULL DEFAULT now()
  , UNIQUE (user_id)
  );

CREATE INDEX ix_market_admins_user_id ON market_admins (user_id);

-- Soft delete for markets (admins can delete a pari)
ALTER TABLE markets ADD COLUMN deleted_at TIMESTAMPTZ;

-- Rebuild users_ext to include new fields
DROP VIEW users_ext;
CREATE VIEW users_ext AS
SELECT
  u.*,
  (
    SELECT full_name
    FROM user_full_names
    WHERE user_id = u.id
    ORDER BY id DESC
    LIMIT 1
  ) as current_full_name,
  (
    SELECT username
    FROM user_usernames
    WHERE user_id = u.id
    ORDER BY id DESC
    LIMIT 1
  ) as current_username,
  EXISTS(
    SELECT 1 FROM market_admins WHERE user_id = u.id
  ) as is_market_admin
FROM
  users u;

-- Rebuild markets_ext to include deleted_at
DROP VIEW markets_ext;
CREATE VIEW markets_ext AS
SELECT
  *,
  (
    SELECT title
    FROM market_titles
    WHERE market_id = markets.id
    ORDER BY id DESC
    LIMIT 1
  ) as current_title,
  (
    SELECT description
    FROM market_descriptions
    WHERE market_id = markets.id
    ORDER BY id DESC
    LIMIT 1
  ) as current_description,
  (
    SELECT id
    FROM resolutions
    WHERE market_id = markets.id
    ORDER BY id DESC
    LIMIT 1
  ) as current_resolution_id
FROM
  markets;

-- migrate:down

DROP VIEW markets_ext;
CREATE VIEW markets_ext AS
SELECT
  *,
  (
    SELECT title
    FROM market_titles
    WHERE market_id = markets.id
    ORDER BY id DESC
    LIMIT 1
  ) as current_title,
  (
    SELECT description
    FROM market_descriptions
    WHERE market_id = markets.id
    ORDER BY id DESC
    LIMIT 1
  ) as current_description,
  (
    SELECT id
    FROM resolutions
    WHERE market_id = markets.id
    ORDER BY id DESC
    LIMIT 1
  ) as current_resolution_id
FROM
  markets;

DROP VIEW users_ext;
CREATE VIEW users_ext AS
SELECT
  *,
  (
    SELECT full_name
    FROM user_full_names
    WHERE user_id = users.id
    ORDER BY id DESC
    LIMIT 1
  ) as current_full_name,
  (
    SELECT username
    FROM user_usernames
    WHERE user_id = users.id
    ORDER BY id DESC
    LIMIT 1
  ) as current_username
FROM
  users;

DROP TABLE market_admins;
ALTER TABLE markets DROP COLUMN deleted_at;
ALTER TABLE users DROP COLUMN last_daily_bonus_at;
ALTER TABLE users DROP COLUMN club_roles;
ALTER TABLE users DROP COLUMN club_user_id;
